server:
  port: 8081

spring:
  application:
    name: ai-insurance
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:}
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GCP_PROJECT_ID:}
          api-key: ${GCP_VERTEX_API_KEY:}
          location: us-central1
          chat:
            options:
              model: gemini-2.5-pro

insurance:
  service:
    base-url: http://localhost:8080